import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { FileText, AlertTriangle, Gavel, CheckCircle } from 'lucide-react';

export default function Terms() {
    return (
        <div className="min-h-screen font-sans text-white selection:bg-brand-500/30 selection:text-brand-200 flex flex-col overflow-x-hidden">
            <Head>
                <title>Terms of Service | Shroud Protocol</title>
                <meta name="description" content="Terms of Service for Shroud Protocol" />
            </Head>

            <Navbar />

            <main className="flex-grow pt-32 pb-20 relative">
                {/* Background Glows */}
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-brand-500/10 rounded-full blur-[128px] pointer-events-none" />
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-accent-500/5 rounded-full blur-[128px] pointer-events-none" />

                <div className="container mx-auto px-6 relative z-10">
                    <div className="max-w-4xl mx-auto">
                        <div className="mb-12 text-center">
                            <h1 className="text-4xl md:text-5xl font-extrabold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">
                                Terms of Service
                            </h1>
                            <p className="text-xl text-gray-400">
                                Rules and regulations for using Shroud Protocol.
                            </p>
                        </div>

                        <div className="glass-panel p-8 md:p-12 rounded-3xl border border-white/10 prose prose-invert max-w-none">
                            <div className="flex items-center space-x-4 mb-8">
                                <div className="p-3 bg-brand-500/10 rounded-xl text-brand-400">
                                    <FileText className="w-8 h-8" />
                                </div>
                                <h2 className="text-2xl font-bold text-white m-0">Agreement to Terms</h2>
                            </div>

                            <p>
                                By accessing or using Shroud Protocol, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services.
                            </p>

                            <h3>1. Description of Service</h3>
                            <p>
                                Shroud Protocol is a decentralized privacy-preserving protocol on the Casper Network. It allows users to deposit assets into a smart contract and withdraw them to a fresh address using Zero-Knowledge Proofs. The protocol is non-custodial; we do not hold or control your funds.
                            </p>

                            <h3>2. User Responsibilities</h3>
                            <p>
                                You are solely responsible for:
                            </p>
                            <ul>
                                <li><strong>Security:</strong> Safeguarding your wallet private keys and the secret keys generated by the protocol. If you lose your secret key, your funds may be permanently lost.</li>
                                <li><strong>Compliance:</strong> Ensuring that your use of Shroud Protocol complies with all applicable laws and regulations in your jurisdiction. You agree not to use the protocol for any illegal activities, including money laundering or financing terrorism.</li>
                            </ul>

                            <h3>3. Risks</h3>
                            <div className="bg-red-500/10 border border-red-500/20 p-6 rounded-2xl my-6">
                                <h4 className="text-red-400 flex items-center mt-0 mb-2">
                                    <AlertTriangle className="w-5 h-5 mr-2" /> Important Risk Warning
                                </h4>
                                <p className="text-sm text-gray-300 mb-0">
                                    Using smart contracts and blockchain technology involves significant risks.
                                </p>
                            </div>
                            <p>
                                You acknowledge and accept the following risks:
                            </p>
                            <ul>
                                <li><strong>Smart Contract Bugs:</strong> While we strive for security, smart contracts may contain bugs or vulnerabilities that could result in the loss of funds.</li>
                                <li><strong>Regulatory Uncertainty:</strong> Blockchain technology and privacy tools are subject to evolving regulations which may impact the availability or legality of the protocol.</li>
                                <li><strong>Network Issues:</strong> Delays, congestion, or failures on the Casper Network may affect transactions.</li>
                            </ul>

                            <h3>4. Limitation of Liability</h3>
                            <p>
                                To the maximum extent permitted by law, Shroud Protocol and its developers shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the protocol.
                            </p>

                            <h3>5. No Warranty</h3>
                            <p>
                                The protocol is provided on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, either express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement.
                            </p>

                            <div className="mt-12 pt-8 border-t border-white/10 text-sm text-gray-500">
                                Last updated: December 1, 2025
                            </div>
                        </div>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
